version: '3'
services: 
    notebook:
        image: jupyter-shortcuts
        container_name: jupyter-shortcuts
        ports: 
            - '8888:8888'
        environment: 
            - JUPYTER_ENABLE_LAB=yes
        # mount to home directory
        volumes:
            - ./:/home/jovyan/work
        command: start-notebook.sh --NotebookApp.token=''